title: Knowledgebase
url: "https://gandhi-97.github.io/base-jekyll-template"
baseurl:
port: 4210
google_analytics_key:
disqus_shortname:
newsletter_action:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /assets/images/kb.png
description: A KnowledgeBase Project.
image: /assets/images/kb.png
author:
  name: JiJi Technologies
  email: contact@jijitechnologies.com
  twitter: jijitech # twitter username without the @ symbol
# social:
#   name: Base Template
#   links:
#     - https://github.com/CloudCannon/base-jekyll-template

# -----
# Build

timezone: "America/Vancouver"
date_format: "%B %-d, %Y"

permalink: /:categories/:title/

plugins:
  - jekyll-extract-element
  - jekyll-sitemap
  # - jekyll-seo-tag
  - jekyll-feed
  - jekyll-archives

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  sets:


jekyll-archives:
  enabled: ['categories']

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
      comments: true
  -
    scope:
      type: "sets"
    values:
      _hide_content: true
  -
    scope:
      path: "index.html"
    values:
      body_class: "show_hero_search"

social_icons:
  - Facebook
  - LinkedIn
  - Twitter
  - YouTube
  - Email

types:
  - Document
  - Video

_comments:
